sensors:
  - id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
    topic: /camera/imu0
    description: "realsense but noise levels are wrong"
    sensor_type: IMU
    sigmas:
      acc_noise_density: 4e-3
      acc_bias_random_walk_noise_density: 4e-3
      gyro_noise_density: 1e-4
      gyro_bias_random_walk_noise_density: 1e-4
    saturation_accel_max_mps2: 150.0
    saturation_gyro_max_radps: 7.5
    gravity_magnitude_mps2: 9.81

  - id: 412eab8e4058621f7036b5e765dfe812
    sensor_type: NCAMERA
    description: "realsense everything is wrong"
    topic: ""
    cameras:
      - camera:
          topic: /camera/cam0
          id: 54812562fa109c40fe90b29a59dd7798
          description: "infra1"
          sensor_type: CAMERA
          line-delay-nanoseconds: 0
          image_height: 480
          image_width: 640
          type: pinhole
          intrinsics:
            cols: 1
            rows: 4
            data: [388.1861572265625,388.1861572265625, 324.527099609375, 235.2352294921875]
          
          distortion:
            type: none
            parameters:
              cols: 1
              rows: 4
              data: [0, 0, 0, 0]
        T_B_C:
          cols: 4
          rows: 4
          data: [1, 0, 0, 0,
                 0, 1, 0, 0,
                 0, 0, 1, 0,
                 0.0, 0.0, 0.0, 1.0]
  
      - camera:
          topic: /camera/cam1
          id: 54812562fa109c40fe90b29a59dd7723
          description: "infra2"
          sensor_type: CAMERA
          line-delay-nanoseconds: 0
          image_height: 480
          image_width: 640
          type: pinhole
          intrinsics:
            cols: 1
            rows: 4
            data: [388.1861572265625,388.1861572265625, 324.527099609375, 235.2352294921875]
          
          distortion:
            type: none
            parameters:
              cols: 1
              rows: 4
              data: [0, 0, 0, 0]
        T_B_C:
          cols: 4
          rows: 4
          data: [1, 0, 0, 0,
                 0, 1, 0, 0,
                 0, 0, 1, 0,
                 0.0, 0.0, 0.0, 1.0]



extrinsics:

  - sensor_id: 412eab8e4058621f7036b5e765dfe812
    base_sensor_id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
    T_B_S:
      cols: 4
      rows: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
    base_sensor_id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

