#!/usr/bin/env bash
# Script to run ROVIOLI from a Euroc live data source (e.g., Euroc bag file with rosbag play).
# Usage: tutorial_euroc <output save folder> [<additional rovioli flags>]

LOCALIZATION_MAP_OUTPUT=$1
SENSOR_CALIBRATION="$ROVIO_CONFIG_DIR/euroc-b.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=0 \
  --sensor_calibration_file=$SENSOR_CALIBRATION  \
  --datasource_type="rostopic" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --map_builder_save_image_as_resources=false \
  --optimize_map_to_localization_map=false $REST
